use std::env;
use std::fs;
use std::path::{Path, PathBuf};

/// Vendored color themes are parsed at build time and emitted as a static
/// `BUILTIN_THEMES` array. Parsing is a tiny TOML-subset state machine —
/// themes use a constrained shape (only `[colors.X]` headers and
/// `key = "#rrggbb"` lines), so we don't pull in a full toml crate.
fn main() {
    println!("cargo:rerun-if-changed=themes");
    println!("cargo:rerun-if-changed=build.rs");

    let themes_dir = Path::new("themes");
    let mut entries: Vec<(String, ParsedTheme)> = Vec::new();

    for dirent in fs::read_dir(themes_dir).expect("read themes/") {
        let path = dirent.expect("dirent").path();
        if path.extension().map(|e| e == "toml").unwrap_or(false) {
            let name = path
                .file_stem()
                .expect("file stem")
                .to_string_lossy()
                .to_string();
            let src = fs::read_to_string(&path)
                .unwrap_or_else(|e| panic!("read {path:?}: {e}"));
            let theme = parse(&src)
                .unwrap_or_else(|e| panic!("parse {path:?}: {e}"));
            entries.push((name, theme));
        }
    }

    entries.sort_by(|a, b| a.0.to_lowercase().cmp(&b.0.to_lowercase()));

    let mut out = String::new();
    out.push_str("// AUTO-GENERATED by build.rs. Do not edit.\n\n");
    out.push_str("pub static BUILTIN_THEMES: &[BuiltinTheme] = &[\n");
    for (name, t) in &entries {
        out.push_str("    BuiltinTheme {\n");
        out.push_str(&format!("        name: {name:?},\n"));
        out.push_str(&format!("        bg: {:?},\n", t.bg));
        out.push_str(&format!("        fg: {:?},\n", t.fg));
        out.push_str(&format!("        cursor_bg: {:?},\n", t.cursor_bg));
        out.push_str(&format!("        cursor_fg: {:?},\n", t.cursor_fg));
        out.push_str(&format!("        palette: {:?},\n", t.palette));
        out.push_str("    },\n");
    }
    out.push_str("];\n");

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    let out_path = out_dir.join("themes_data.rs");
    fs::write(&out_path, out).unwrap_or_else(|e| panic!("write {out_path:?}: {e}"));

    println!("cargo:warning=themes: {} vendored", entries.len());
}

#[derive(Default)]
struct ParsedTheme {
    bg: [u8; 3],
    fg: [u8; 3],
    cursor_bg: [u8; 3],
    cursor_fg: [u8; 3],
    palette: [[u8; 3]; 16],
}

/// Tiny TOML-subset parser tailored to the iTerm2-Color-Schemes Alacritty
/// format. Recognizes `[colors.<group>]` section headers and
/// `<key> = "#rrggbb"` lines. Comments (`#`) and empty lines are ignored.
fn parse(src: &str) -> Result<ParsedTheme, String> {
    let mut t = ParsedTheme::default();
    let mut section: Option<String> = None;
    let mut got_bg = false;
    let mut got_fg = false;
    let mut palette_set = [false; 16];

    for (lineno, raw) in src.lines().enumerate() {
        let line = strip_comment(raw).trim();
        if line.is_empty() {
            continue;
        }
        if let Some(rest) = line.strip_prefix('[').and_then(|l| l.strip_suffix(']')) {
            section = Some(rest.to_string());
            continue;
        }
        // key = "value"
        let (key, value) = line
            .split_once('=')
            .ok_or_else(|| format!("line {}: missing `=`", lineno + 1))?;
        let key = key.trim();
        let value = value.trim().trim_matches('"');
        let rgb = parse_hex(value)
            .ok_or_else(|| format!("line {}: bad color {value:?}", lineno + 1))?;
        let sec = section.as_deref().unwrap_or("");
        match (sec, key) {
            ("colors.primary", "background") => {
                t.bg = rgb;
                got_bg = true;
            }
            ("colors.primary", "foreground") => {
                t.fg = rgb;
                got_fg = true;
            }
            ("colors.cursor", "text") => t.cursor_fg = rgb,
            ("colors.cursor", "cursor") => t.cursor_bg = rgb,
            ("colors.normal", name) => {
                if let Some(idx) = ansi_name_to_index(name, false) {
                    t.palette[idx] = rgb;
                    palette_set[idx] = true;
                }
            }
            ("colors.bright", name) => {
                if let Some(idx) = ansi_name_to_index(name, true) {
                    t.palette[idx] = rgb;
                    palette_set[idx] = true;
                }
            }
            _ => {} // ignore unknown sections (selection, search, etc.)
        }
    }

    if !got_bg || !got_fg {
        return Err("missing background/foreground".into());
    }
    for (i, set) in palette_set.iter().enumerate() {
        if !set {
            return Err(format!("missing palette[{i}]"));
        }
    }
    // Reasonable defaults if the theme didn't specify cursor colors.
    if t.cursor_bg == [0, 0, 0] && t.cursor_fg == [0, 0, 0] {
        t.cursor_bg = t.fg;
        t.cursor_fg = t.bg;
    }
    Ok(t)
}

fn strip_comment(line: &str) -> &str {
    // Comment is `#` not inside a string. Themes don't have hashes inside
    // strings except for color literals like "#1d1d1d", so we cheat: a `#`
    // outside of `"..."` starts a comment. Simple state machine.
    let bytes = line.as_bytes();
    let mut in_str = false;
    for (i, &b) in bytes.iter().enumerate() {
        if b == b'"' {
            in_str = !in_str;
        } else if b == b'#' && !in_str {
            return &line[..i];
        }
    }
    line
}

fn parse_hex(s: &str) -> Option<[u8; 3]> {
    let s = s.trim_start_matches('#');
    if s.len() != 6 {
        return None;
    }
    let r = u8::from_str_radix(&s[0..2], 16).ok()?;
    let g = u8::from_str_radix(&s[2..4], 16).ok()?;
    let b = u8::from_str_radix(&s[4..6], 16).ok()?;
    Some([r, g, b])
}

fn ansi_name_to_index(name: &str, bright: bool) -> Option<usize> {
    let base = match name {
        "black" => 0,
        "red" => 1,
        "green" => 2,
        "yellow" => 3,
        "blue" => 4,
        "magenta" => 5,
        "cyan" => 6,
        "white" => 7,
        _ => return None,
    };
    Some(if bright { base + 8 } else { base })
}
